name: Execute Cloud Run Jobs 

on:
  schedule:
    # - cron: "0 0 * * 1" # 週1回実行　
    - cron: "0 0 1 * *" # 月1回実行

permissions:
  id-token: write

env:
  PROJECT_ID: gig-sample-383607
  REGION: asia-northeast1
  WORKLOAD_IDENTITY_PROVIDER: projects/908674848704/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
  SERVICE_ACCOUNT: github-actions@gig-sample-383607.iam.gserviceaccount.com

jobs:
  execute-cloudrun-jobs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate Google Cloud
        id: auth
        uses: google-github-actions/auth@v1.1.1
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Execute Cloud Run Jobs
        run: |
          gcloud run jobs execute add-vector-data \
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }}
